# Generated by Django 4.1.1 on 2022-10-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('file_upload', models.FileField(null=True, upload_to='forms')),
            ],
        ),
    ]
