# Generated by Django 4.1.1 on 2022-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_applicationforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testiomonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='services')),
                ('tag', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
