# Generated by Django 4.1.1 on 2022-10-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_testiomonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testiomonial',
            new_name='Testimonial',
        ),
    ]
