# Generated by Django 4.1.1 on 2022-09-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alabrarAdmin', '0002_alter_customer_name_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='design_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alabrarAdmin.designtype'),
        ),
    ]
