# Generated by Django 4.1.1 on 2022-09-15 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alabrarAdmin', '0003_alter_jobitem_design_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alabrarAdmin.job'),
        ),
    ]
