# Generated by Django 4.1.1 on 2022-09-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabrarAdmin', '0005_job_total_job_total_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
