# Generated by Django 4.1.1 on 2022-09-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alabrarAdmin', '0007_staff_address_staff_email_staff_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemexpenditure',
            name='recieved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alabrarAdmin.staff'),
        ),
    ]
