# Generated by Django 4.1.1 on 2022-10-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alabrarAdmin', '0010_remove_staffwage_qauntity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffwage',
            old_name='totat_amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='staffwage',
            old_name='totat_amount_currency',
            new_name='total_amount_currency',
        ),
    ]
