# Generated by Django 4.1.1 on 2022-10-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alabrarAdmin', '0011_rename_totat_amount_staffwage_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumables',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='consumables',
            old_name='price_currency',
            new_name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='itemexpenditure',
            name='quantity',
        ),
    ]
