# Generated by Django 4.1.1 on 2022-10-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabrarAdmin', '0012_rename_price_consumables_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumables',
            options={'ordering': ['item']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='designtype',
            options={'ordering': ['type_name']},
        ),
        migrations.AlterModelOptions(
            name='itemexpenditure',
            options={'ordering': ['-incurred_on']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-recieved', '-collection_date']},
        ),
        migrations.AlterModelOptions(
            name='jobitem',
            options={'ordering': ['job']},
        ),
        migrations.AlterModelOptions(
            name='kaftanmeasurement',
            options={'ordering': ['customer']},
        ),
        migrations.AlterModelOptions(
            name='shirtmeasurement',
            options={'ordering': ['customer']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='staffactivity',
            options={'ordering': ['-done_on']},
        ),
        migrations.AlterModelOptions(
            name='staffwage',
            options={'ordering': ['-paid_on']},
        ),
        migrations.AlterModelOptions(
            name='trousermeasurement',
            options={'ordering': ['customer']},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
