# Generated by Django 4.1.1 on 2022-10-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabrarAdmin', '0015_remove_sell_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sms_text',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
