# Generated by Django 4.1.1 on 2022-10-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabrarAdmin', '0016_job_sms_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sms_text',
            field=models.BooleanField(default=True),
        ),
    ]
